services:
  - type: web
    name: news-whatsapp-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: FROM_WHATSAPP_NUMBER
        sync: false
